version: "3.9"
services:
  db:
    image: postgres:14.5
    container_name: "${DOCKER_COMPOSE_CONTAINER_BASE_NAME}_DB"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
