version: "3.9"
services:
  db:
    image: postgres:14.5
    container_name: "${DOCKER_COMPOSE_CONTAINER_BASE_NAME}_DB"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.dev
